version: "3"
services:
       node-server:
           container_name: node-server
           image: server
           environment:
             - PORT=8000
           restart: always
           build: .
           ports:
             - "8000:8000"
           links:
             - mongodb
       mongodb:
             container_name: mongodb
             image: mongo
             ports:
               - '27018:27017'
             volumes:
               - type: volume
                 source: mongodb_data_volume
                 target: /data/db
volumes:
       mongodb_data_volume:
             external: false
