version: "3"
services:
       node-server:
           container_name: node-server
           image: tonycook/mission6
           environment:
             - PORT=8000
           restart: always
           build: .
           ports:
             - "8000:8000"
           links:
             - mongodb
       mongodb:
             container_name: mongodb
             image: mongo
             ports:
               - '27018:27017'